### ISSUE TITLE
/robot/front_laser/scan and /robot/rear_laser/scan publish no data

### ISSUE THREAD

**Issue by scploeger** [RobotnikAutomation/rbkairos_sim#10]
Hi,
By following instructions in the Readme, I am able to launch the sim, and everything looks okay. A gazebo and RViz window launch as expected. However, the lidar does not produce a laser scan.
When echoing the `/robot/front_laser/scan` and `/robot/rear_laser/scan` topics, the following is returned `WARNING: no messages received and simulated time is active.
Is /clock being published?`

The laser shows up in the Gazebo sim, and the topics show up in the RViz "Displays" box, but no data comes up under the topics.

Any help to figure out why the lasers publish no data would be much appreciated! Thank you

Spencer

**Comment by alex-arnal** [comment]
Hi, Spencer

It is possible that the problem is due to something related to the laser gazebo plugin that uses the GPU drivers. I understand you are using ROS Melodic. Could you tell me the version of Gazebo you are using? 

On the one hand, you could try installing the Gazebo plugins and try again launching the simulation, just in case you don't have them installed (this is probably not the problem).

```bash
sudo apt-get install ros-melodic-gazebo-plugins
```

On the other hand, I have updated the simulation to select to use or not the Gazebo GPU plugin for the lasers by argument. If you download the simulation again following the README, you should have the latest changes. Once you have updated the simulation you just need to launch it using the argument use_gpu:=false

```bash
roslaunch rbkairos_sim_bringup rbkairos_complete.launch use_gpu:=true
```

Let me know when you try it. I hope it works
Álex

**Comment by scploeger** [comment]
Hi Alex, thanks. I reinstalled the plugins and everything is working well now. Thanks for the advice.
