### ISSUE TITLE
No laser scan received when launching sim with moveit

### ISSUE THREAD

**Issue by scploeger** [RobotnikAutomation/rbkairos_sim#14]
Hello,

**When launching the sim with moveit, as per the readme instructions using:**
`roslaunch rbkairos_sim_bringup rbkairos_complete.launch moveit_movegroup_a:=true`
the robot cannot localize, and the following error appears in the terminal:
`[ WARN] [1638367025.481971188, 167.087000000]: No laser scan received (and thus no pose updates have been published) for 167.087000 seconds.  Verify that data is being published on the /robot/front_laser/scan topic.`
`[ WARN] [1638367028.801871110, 170.300000000]: Timed out waiting for transform from robot_base_footprint to robot_map to become available before running costmap, tf error: canTransform: target_frame robot_map does not exist.. canTransform returned after 0.1 timeout was 0.1.`
When inspecting the front or rear laser scan topic with `rostopic echo`, it does appear like the lasers are correctly publishing scan as they should. So somehow, launching moveit is causing amcl or rviz to not recieve the data.

**When launching the sim without moveit using:**
`roslaunch rbkairos_sim_bringup rbkairos_complete.launch`
the simulation launches fine, the lasers seem to be working okay, and the robot can localize successfully. So it seems to be a problem that only exists when the sim is launched with moveit.

I have also tried launching the sim without moveit, then starting the moveit demo package separately. This seems to work at first, since everything launches successfully, but when trying to use moveit, the planner fails to plan a path every time.

I have tested this on Ubuntu 18.04 using ROS 18.04. For these tests, a fresh copy of the repo was created as per the instructions in the readme. Any help is appreciated, thanks!

-- Spencer

**Comment by alex-arnal** [comment]
Hi Spencer,

I have been capable to solve (I hope) the issue in this [commit](https://github.com/RobotnikAutomation/rbkairos_sim/commit/8cae9f78b6f283689b0b8e6cbe339f600e1f6551). It seems that the problem was that the robot_description was loaded two times, but I don't really know if this was the main problem. For me, it started to work after that change. 

I have also updated some of the dependencies to avoid some warnings, so feel free to update your workspace and let me know if it is working for you now.

Sorry for late response,
Álex
