### ISSUE TITLE
BUG: load_kinematics_file

### ISSUE THREAD

**Issue by marbosjo** [RobotnikAutomation/rbkairos_sim#4]
As far as I know, kinematics file is for loading a calibrated kinematics file for a real arm.

- If arm control is done by default using UR controller, and not through ROS, kinematics file is not needed.
- In rbkairos_control, arm control is only used in simulation.
- If it is required to load a kinematics file, then a sample file should be included in repository, so it can run as it is.

PS: I'm talking about new_structure branch.

**Comment by alex-arnal** [comment]
As you say, the kinematics file is only used for a real arm.

Exists one version of the description packages of UR that does not require the kinematics file but now we are using the official [UR driver](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver) for ROS that actually requires the kinematics file, even if you are not controlling the arm through ROS, because it is a required parameter of the arm macro in the URDF. 

When we are using the real arm with ROS, we use the standard setup provided by UR. [Here](https://github.com/RobotnikAutomation/summit_xl_robot/tree/kinetic-devel/summit_xl_bringup/launch/arm/ur) you can see how the control of the real arm is launched. For sim we are just using position controllers. This explains why the control for the arm is only specified for simulation in rbkairos_control. Maybe if we are only using UR arms, then the control for the real arm could be standardized and moved to the rbkairos_control too. 

I thought that the way to go should be using the same packages in both cases (simulation and real robot) and try to make the simulation as close as the real robot, that is why load_kinematics_file is being used for the simulation (even if not really useful).

[Here](https://github.com/RobotnikAutomation/rbkairos_common/tree/kinetic-devel/rbkairos_control/config) you have some examples for calibration config.

**Comment by marbosjo** [comment]
Please provide and load a standard file for simulation, so it can run right just after cloning the repo.

Or maybe I'm missing something.

**Comment by marbosjo** [comment]
By the way... where is package egh_gripper_description ?

**Comment by alex-arnal** [comment]
Sorry but you are definitely missing something, I tested the simulation before answering you and it is working for me. Any case, following the [README.md](https://github.com/RobotnikAutomation/rbkairos_sim/blob/new_structure/README.md) file.

1. Download the repo itself in the workspace:
```bash
git clone  https://github.com/RobotnikAutomation/rbkairos_sim.git
```
2. Checkout to the new_structure branch:
```bash
git checkout new_structure
```
These two first steps are not explicitly put in the readme but... they are understood

3. Taking a look at the section on dependencies... We need rbkairos_common first:
```bash
git clone https://github.com/RobotnikAutomation/rbkairos_common.git
```
4. Which in turn depends on summit_xl_common:
```bash
git clone https://github.com/RobotnikAutomation/summit_xl_common.git
```
5. This last also depends on robotnik_sensors:
```bash
git clone https://github.com/RobotnikAutomation/robotnik_sensors.git
```

6. Going back to the dependencies section... The official UR driver for ROS is necessary, as the README.md says, it is really important following the README of the UR driver to make the thing work. Let's clone it:

```bash
git clone https://github.com/UniversalRobots/Universal_Robots_ROS_Driver
```

7.  The UR driver for ROS depends on fmauch_universal_robot repository, so let's clone it
```bash
 git clone -b calibration_devel https://github.com/fmauch/universal_robot.git fmauch_universal_robot
```

8. At this point you can build the workspace and try launching the simulation:
```bash
roslaunch rbkairos_sim_bringup rbkairos_complete.launch
```
The description of the robot it is always getting the kinematics_file from the config folder of the rbkairos_control packages, as mentioned before in this thread... The kinematics file are [HERE](https://github.com/RobotnikAutomation/rbkairos_common/tree/kinetic-devel/rbkairos_control/config)

egh_description is here: [https://github.com/RobotnikAutomation/egh_gripper_common](https://github.com/RobotnikAutomation/egh_gripper_common)

Since the branch has been pending merge for two months, there may be changes in the kinetic-devel branch that have not been applied to this branch (dependencies, readme update, etc). Sorry about that.

But following the steps that I listed above, it's working for me.

**Comment by marbosjo** [comment]
Why not using these files https://github.com/RobotnikAutomation/rbkairos_common/tree/kinetic-devel/rbkairos_control/config as the default kinematic files, instead of the ones in other repo?

This way the dependencies are reduced and you don't need a huge package such as the UR.

**Comment by alex-arnal** [comment]
The RB-Kairos description are already using them. I am not understanding where is the problem, sorry.

https://github.com/RobotnikAutomation/rbkairos_common/blob/437cce06c0d05a8136365b690656ef0902a91530/rbkairos_description/robots/rbkairos_ur10.urdf.xacro#L105

**Comment by marbosjo** [comment]
Ok, new_structure is not updated.
